# 异常处理
golang中使用defer,panic,recover处理异常,类似于其他语言的处理机制，抛出异常，在defer中通过recover捕获异常，然后处理异常 

### defer 
> defer主要用于函数中，在函数结束时(正常或者异常情况下)调用执行，在defer中可以添加函数等，释放资源，改变返回值等  
> defer函数可以调用多次，形成一个defer栈，后进先出，后进得先被调用   

### panic  
> 内置函数，接收一个interface{}类型得值(任意值)作为参数，直接触发异常，panic如果没有处理，会导致程序挂掉，除非是在recover中处理，如果函数执行时候出发panic了，函数不向下走，并不是直接向上层传递panic，而是调用defer处理函数，等defer处理完后，panic再向上层传递或者结束  

### recover  
> panic在函数中触发时，并不会立即返回，而是先调用defer,在defer中如果有办法将panix捕获饼阻止panic传递，panic即结束。recover之后，逻辑并不会恢复到panic那个点，而是在defer调用后返回


### 例子  
``` go
package main               
                           
import (                   
        "fmt"              
        "math/rand"        
        "time"             
)                          
                           
func CoverPanic() {        
        defer func() {   
                if err := recover(); err != nil {
                        fmt.Println("error:", err)
                        //可以恢复，看使用环境
                        //      go CoverPanic()
                        return
                }          
        }()                
        rand.Seed(time.Now().UnixNano())
        for {              
                x := rand.Intn(10)
                if x == 5 {
                        fmt.Println("goroutine", x)
                        panic("手动调用panic")
                } else {
                        fmt.Println("time:", x)
                }          
        }                  
}                          
func main() {              
        fmt.Println("vim-go")
        go CoverPanic() 
        time.Sleep(time.Second * 30) 
        //      select {}                                                                                                                                                                                                                                                     
}  
```